apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: card-transactions
  labels:
    strimzi.io/cluster: my-cluster
  namespace: kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
