apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service-a
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service-a
  template:
    metadata:
      labels:
        app: kafka-service-a
    spec:
      containers:
        - name: kafka-service-a
          image: kafka-service-a:0.0.1
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.kafka:9092"
