apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-operator-s
  namespace: kafka
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /metrics
      targetPort: 9404
      scheme: http
  selector:
    matchLabels:
      kafka-metrics: 'true'